### ISSUE TITLE
Add captcha for registration (or disable signup during BETA)

### ISSUE THREAD

**Issue by sarathms** [fsmk/FSMK-Website#18]
I haven't checked this yet. But I see hundreds of notification mails about registrations being made on this account. If registration is open, its a horrible security hole right now. Disable registrations until out of beta. Else enable a free captcha service (not from Google) to avoid bot registrations.

**Comment by shijiltv** [comment]
I have set  "Only site administrators can create new user accounts" options. This should resolve the issue for the time being. I have also deleted those dummy accounts.
